media:
  path: images
  public: /images

content:
  - name: products
    label: Products
    type: collection
    path: products
    format: json
    fields:
      - name: title
        label: Name
        type: string
      - name: price
        label: Price
        type: number
      - name: category
        label: Category
        type: select
        options:
          - value: vegetables
            label: Vegetables
          - value: fruits
            label: Fruits
          - value: grains
            label: Grains
          - value: dairy
            label: Dairy
      - name: tags
        label: Tags
        type: list
      - name: image
        label: Image
        type: image
      - name: body
        label: Description
        type: rich-text
        
