backend:
  name: github
  repo: buildawesomesites-creator/invieorganicshop
  branch: main
  base_url: https://api.github.com # This helps the script attempt a connection

local_backend: true # This forces the CMS to show the UI even if authentication is pending

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Category", name: "category", widget: "select", options: ["Vegetables", "Fruits", "Grains", "Dairy"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
      
